# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/Desktop/cv_model

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/Desktop/cv_model

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/Desktop/cv_model/CMakeFiles /home/ubuntu/Desktop/cv_model/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/Desktop/cv_model/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cv_ransac

# Build rule for target.
cv_ransac: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cv_ransac
.PHONY : cv_ransac

# fast build rule for target.
cv_ransac/fast:
	$(MAKE) -f CMakeFiles/cv_ransac.dir/build.make CMakeFiles/cv_ransac.dir/build
.PHONY : cv_ransac/fast

#=============================================================================
# Target rules for targets named cv_ellipse

# Build rule for target.
cv_ellipse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cv_ellipse
.PHONY : cv_ellipse

# fast build rule for target.
cv_ellipse/fast:
	$(MAKE) -f CMakeFiles/cv_ellipse.dir/build.make CMakeFiles/cv_ellipse.dir/build
.PHONY : cv_ellipse/fast

cv_ellipse.o: cv_ellipse.cpp.o

.PHONY : cv_ellipse.o

# target to build an object file
cv_ellipse.cpp.o:
	$(MAKE) -f CMakeFiles/cv_ellipse.dir/build.make CMakeFiles/cv_ellipse.dir/cv_ellipse.cpp.o
.PHONY : cv_ellipse.cpp.o

cv_ellipse.i: cv_ellipse.cpp.i

.PHONY : cv_ellipse.i

# target to preprocess a source file
cv_ellipse.cpp.i:
	$(MAKE) -f CMakeFiles/cv_ellipse.dir/build.make CMakeFiles/cv_ellipse.dir/cv_ellipse.cpp.i
.PHONY : cv_ellipse.cpp.i

cv_ellipse.s: cv_ellipse.cpp.s

.PHONY : cv_ellipse.s

# target to generate assembly for a file
cv_ellipse.cpp.s:
	$(MAKE) -f CMakeFiles/cv_ellipse.dir/build.make CMakeFiles/cv_ellipse.dir/cv_ellipse.cpp.s
.PHONY : cv_ellipse.cpp.s

cv_ransac.o: cv_ransac.cpp.o

.PHONY : cv_ransac.o

# target to build an object file
cv_ransac.cpp.o:
	$(MAKE) -f CMakeFiles/cv_ransac.dir/build.make CMakeFiles/cv_ransac.dir/cv_ransac.cpp.o
.PHONY : cv_ransac.cpp.o

cv_ransac.i: cv_ransac.cpp.i

.PHONY : cv_ransac.i

# target to preprocess a source file
cv_ransac.cpp.i:
	$(MAKE) -f CMakeFiles/cv_ransac.dir/build.make CMakeFiles/cv_ransac.dir/cv_ransac.cpp.i
.PHONY : cv_ransac.cpp.i

cv_ransac.s: cv_ransac.cpp.s

.PHONY : cv_ransac.s

# target to generate assembly for a file
cv_ransac.cpp.s:
	$(MAKE) -f CMakeFiles/cv_ransac.dir/build.make CMakeFiles/cv_ransac.dir/cv_ransac.cpp.s
.PHONY : cv_ransac.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... cv_ransac"
	@echo "... edit_cache"
	@echo "... cv_ellipse"
	@echo "... cv_ellipse.o"
	@echo "... cv_ellipse.i"
	@echo "... cv_ellipse.s"
	@echo "... cv_ransac.o"
	@echo "... cv_ransac.i"
	@echo "... cv_ransac.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

